### ISSUE TITLE
How can I notify a server that a resource is changed?

### ISSUE THREAD

**Issue by davideicardi** [AllSmartObjects/smartobject#19]
I have used smart object to create a device with some resources. Some resources are read only (for example 5/0/3, firmware update state).
My server is observing these resources.

**How can I notify the server that the resource is changed?**

If I call `so.write` from the device I get an error that the resource is not writable.
For now I have just created a `read` callback that allow the server to read the value but it is not notified if the value change.

**Comment by PeterEB** [comment]
Hi davideicardi,

> How can I notify the server that the resource is changed?

smartobject does not have the diff function in `so.read`. So you can add diff and notify functions in `so.read` callback. Or you can replace smartobject instance function `so.read` like the following:
```js
so.__read = so.read;
so.read = function (oid, iid, rid, opt, callback) {
    if (typeof opt === 'function') {
        callback = opt;
        opt = undefined;
    }

    return so.__read(oid, iid, rid, opt, function (err, data) {
        // You can add diff and notify functions here.
        
        callback(err, data);
    });
};
```

> If I call so.write from the device I get an error that the resource is not writable.

The **State** resource in [LwM2M Firmware Update Object](https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?url=http%3A%2F%2Fopenmobilealliance.org%2Ftech%2Fprofiles%2FLWM2M_Firmware_Update-v1_0_2.xml) is only readable. So you can init the State resource as an [object with read method](https://github.com/AllSmartObjects/smartobject/blob/master/docs/resource_plan.md#2-resource-value-is-a-spec-object).

**Comment by davideicardi** [comment]
Thanks PeterEB!

But how can I notify the server? Can you just point me to the right piece of code?
Writable resources are correctly notified to the server when the value change so I suppose that there is a way to notify the server using smart object.

Maybe I'm not understanding your idea, but I would expect to have a method like `so.notify`.

Do you think that can be useful to better implement this scenario? I can try to do a PR ...

**Comment by PeterEB** [comment]
smartobject is a data model. The notify function should be implement in the client library or application who use smartobject. Like [coap-node](https://github.com/PeterEB/coap-node) or [mqtt-node](https://github.com/lwmqn/mqtt-node). 

You can refer to [here](https://github.com/lwmqn/mqtt-node/blob/master/lib/init.js#L117). mqtt-node is a client node of MQTT machine network. It overwrite smartobject instance function `so.read`. In mqtt-node, `so.read` check the data change and report to server.

**Comment by davideicardi** [comment]
Thanks @PeterEB !  Calling `read` solve the problem.
